/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

/**
 *
 * @author Ruben
 */
public class FrameEncuesta extends javax.swing.JFrame {

    /**
     * Creates new form FrameEncuesta
     */
    public FrameEncuesta() {
        initComponents();
    }
    
    public void crearWord(String opcion){
        // Crear un nuevo documento de Word
        XWPFDocument documento = new XWPFDocument();
        
        // Crear un título
        XWPFParagraph titulo = documento.createParagraph();
        titulo.setAlignment(ParagraphAlignment.CENTER); // Centrar el título
        XWPFRun runTitulo = titulo.createRun();
        runTitulo.setText("Título del Documento");
        runTitulo.setBold(true); // Establecer el texto en negrita
        runTitulo.setFontSize(20); // Establecer tamaño de fuente para el título
        titulo.setSpacingAfter(200); // Espacio después del título


        // Crear un párrafo
        XWPFParagraph parrafo = documento.createParagraph();
        XWPFRun run = parrafo.createRun();
        run.setText("La respuesta a la primera pregunta es:");
        run.addBreak();  // Esto agrega un salto de línea
        run.setText(opcion);
        run.setFontSize(14);
         // Obtener la fecha y hora del sistema
        String formato = "yyyy-MM-dd_HH-mm-ss"; // Formato de fecha y hora
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        String fechaYHora = sdf.format(new Date());
        
        // Crear el nombre del archivo
        String nombreArchivo = "C:/ejemplo_" + fechaYHora + ".docx";
        

        // Guardar el documento en el disco C:
        try (FileOutputStream out = new FileOutputStream(nombreArchivo)) {
            documento.write(out);
            //System.out.println("Documento creado exitosamente en " + nombreArchivo);
            JOptionPane.showMessageDialog(rootPane, "Los datos se han enviado");
        } catch (IOException e) {
            //System.err.println("Error al crear el documento: " + e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error al crear el documento: " + e.getMessage());
        } finally {
            // Cerrar el documento
            try {
                documento.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        
        /* System.out.println("Presiona Enter para cerrar el programa...");

        // Crear un objeto Scanner para leer la entrada del usuario
        Scanner scanner = new Scanner(System.in);

        // Esperar a que el usuario presione Enter
        scanner.nextLine();

        // Cerrar el scanner
        scanner.close();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PREGUNTA 1");

        buttonGroup1.add(rb1);
        rb1.setText("Respuesta 1");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb2);
        rb2.setText("Respuesta 2");
        rb2.setName(""); // NOI18N

        buttonGroup1.add(rb3);
        rb3.setText("Respuesta 3");

        jButton.setText("Enviar respuesta");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton)
                            .addComponent(rb1))
                        .addGap(18, 18, 18)
                        .addComponent(rb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb3)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addComponent(rb3))
                .addGap(56, 56, 56)
                .addComponent(jButton)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        //JOptionPane.showMessageDialog(rootPane, "Eoooo");
        String op;
        if (rb1.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Opcion1");
            op = "Opción 1";
        }
        else if(rb2.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Opcion2");
            op = "Opción 2";
        }
        else if(rb3.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Opcion3");
            op = "Opción 3";
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado nada");
            op = "No ha elegido ninguna respuesta";
        }
        
        crearWord(op);
        
    }//GEN-LAST:event_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    // End of variables declaration//GEN-END:variables
}
